baseurl = "/"
languageCode = "en-us"
title = "J Cunningham!"
# theme = "hugo-lithium"
theme = "hermit"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    latin = "/latin/:slug"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/post/"
[[menu.main]]
    name = "Latin Learning"
    url = "/latin/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cunningjames"

[params]
    description = "Personal website for stuff."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    [params.logo]
    url = "rabbit-logo.png"
    width = 50
    height = 50
    alt = "Logo"

    author = "James Cunningham"
    dateFormat = "2006-01-02"